# Generated by Django 4.0.4 on 2022-04-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='회사명'),
        ),
    ]
