# Generated by Django 4.0.4 on 2022-04-13 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '회사'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '구역'},
        ),
        migrations.AddField(
            model_name='section',
            name='latitude',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='section',
            name='longitude',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='경도'),
        ),
    ]
