# Generated by Django 4.0.4 on 2022-04-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_section_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='companies.company'),
        ),
    ]
