# Generated by Django 4.0.4 on 2022-04-13 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_section_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='latitude',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='section',
            name='longitude',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='경도'),
        ),
    ]
