# Generated by Django 4.0.4 on 2022-04-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_abstractitem_remove_company_title_companylist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('abstractitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='companies.abstractitem')),
            ],
            options={
                'verbose_name_plural': 'RiskFactor',
            },
            bases=('companies.abstractitem',),
        ),
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='risk_factor',
            field=models.ManyToManyField(blank=True, related_name='risk_factor', to='companies.riskfactor'),
        ),
    ]
